size: 15
bonuses:
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 0
    column: 0
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 0
    column: 7
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 0
    column: 14
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 1
    column: 6
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 1
    column: 8
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 6
    column: 1
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 6
    column: 13
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 7
    column: 0
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 7
    column: 7
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 7
    column: 14
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 8
    column: 1
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 8
    column: 13
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 13
    column: 6
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 13
    column: 8
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 14
    column: 0
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 14
    column: 7
  - kind: category_multiplier
    multiplier: 3
    category: red
    row: 14
    column: 14
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 0
    column: 5
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 0
    column: 9
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 1
    column: 4
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 1
    column: 10
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 2
    column: 3
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 2
    column: 11
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 3
    column: 2
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 3
    column: 12
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 4
    column: 1
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 4
    column: 13
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 5
    column: 0
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 5
    column: 14
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 9
    column: 0
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 9
    column: 14
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 10
    column: 1
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 10
    column: 13
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 11
    column: 2
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 11
    column: 12
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 12
    column: 3
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 12
    column: 11
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 13
    column: 4
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 13
    column: 10
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 14
    column: 5
  - kind: category_multiplier
    multiplier: 3
    category: green
    row: 14
    column: 9
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 5
    column: 7
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 6
    column: 6
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 6
    column: 8
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 7
    column: 5
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 7
    column: 9
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 8
    column: 6
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 8
    column: 8
  - kind: category_multiplier
    multiplier: 3
    category: blue
    row: 9
    column: 7
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 2
    column: 7
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 3
    column: 6
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 3
    column: 8
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 4
    column: 5
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 4
    column: 9
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 5
    column: 4
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 5
    column: 10
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 6
    column: 3
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 6
    column: 11
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 7
    column: 2
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 7
    column: 12
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 8
    column: 3
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 8
    column: 11
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 9
    column: 4
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 9
    column: 10
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 10
    column: 5
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 10
    column: 9
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 11
    column: 6
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 11
    column: 8
  - kind: category_multiplier
    multiplier: 3
    category: yellow
    row: 12
    column: 7
  - kind: word_multiplier
    multiplier: 2
    row: 2
    column: 5
  - kind: word_multiplier
    multiplier: 2
    row: 2
    column: 9
  - kind: word_multiplier
    multiplier: 2
    row: 3
    column: 4
  - kind: word_multiplier
    multiplier: 2
    row: 3
    column: 10
  - kind: word_multiplier
    multiplier: 2
    row: 4
    column: 3
  - kind: word_multiplier
    multiplier: 2
    row: 4
    column: 11
  - kind: word_multiplier
    multiplier: 2
    row: 5
    column: 2
  - kind: word_multiplier
    multiplier: 2
    row: 5
    column: 12
  - kind: word_multiplier
    multiplier: 2
    row: 9
    column: 2
  - kind: word_multiplier
    multiplier: 2
    row: 9
    column: 12
  - kind: word_multiplier
    multiplier: 2
    row: 10
    column: 3
  - kind: word_multiplier
    multiplier: 2
    row: 10
    column: 11
  - kind: word_multiplier
    multiplier: 2
    row: 11
    column: 4
  - kind: word_multiplier
    multiplier: 2
    row: 11
    column: 10
  - kind: word_multiplier
    multiplier: 2
    row: 12
    column: 5
  - kind: word_multiplier
    multiplier: 2
    row: 12
    column: 9
  - kind: word_multiplier
    multiplier: 3
    row: 0
    column: 2
  - kind: word_multiplier
    multiplier: 3
    row: 0
    column: 12
  - kind: word_multiplier
    multiplier: 3
    row: 2
    column: 0
  - kind: word_multiplier
    multiplier: 3
    row: 2
    column: 14
  - kind: word_multiplier
    multiplier: 3
    row: 12
    column: 0
  - kind: word_multiplier
    multiplier: 3
    row: 12
    column: 14
  - kind: word_multiplier
    multiplier: 3
    row: 14
    column: 2
  - kind: word_multiplier
    multiplier: 3
    row: 14
    column: 12
