import type { Schemas } from "./views";

export type Part = Schemas["PartOfSpeech"];
export type Case = Schemas["Case"];
export type GrammaticalNumber = Schemas["Number"];
export type Gender = Schemas["Gender"];
export type Person = Schemas["Person"];
export type Tense = Schemas["Tense"];
export type Mood = Schemas["Mood"];
export type Aspect = Schemas["Aspect"];
export type Degree = Schemas["Degree"];
export type VerbForm = Schemas["VerbForm"];
export type NumeralType = Schemas["NumeralType"];
export type PronounType = Schemas["PronounType"];
export type Quality = Schemas["Quality"];
export type Inflection = Schemas["Inflection"];
export type InflectedForm = Schemas["InflectedForm"];
export type LoreReading = Schemas["LoreReading"];
export type WordLore = Schemas["WordLore"];
export type WordLoreResponse = Schemas["WordLoreResponse"];
