/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Serve Index */
        readonly get: operations["serve_index__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/invitations/{code}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read Invitation */
        readonly get: operations["read_invitation_invitations__code__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/offerings": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Offerings */
        readonly get: operations["list_offerings_offerings_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/presets": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Offered Presets */
        readonly get: operations["list_offered_presets_presets_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/style": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read Style */
        readonly get: operations["read_style_style_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Table */
        readonly post: operations["create_table_tables_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{code}/join": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Join Table */
        readonly post: operations["join_table_tables__code__join_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Describe Table */
        readonly get: operations["describe_table_tables__table_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Stream Events */
        readonly get: operations["stream_events_tables__table_id__events_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/highlights": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Table Highlights */
        readonly get: operations["table_highlights_tables__table_id__highlights_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/lore": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read Lore */
        readonly get: operations["read_lore_tables__table_id__lore_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/moves": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Submit Move */
        readonly post: operations["submit_move_tables__table_id__moves_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/premove": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Cancel Premove */
        readonly delete: operations["cancel_premove_tables__table_id__premove_delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/rack": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Arrange Rack */
        readonly put: operations["arrange_rack_tables__table_id__rack_put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/view": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Table View */
        readonly get: operations["table_view_tables__table_id__view_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tables/{table_id}/words": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Judge Words */
        readonly get: operations["judge_words_tables__table_id__words_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccentTokens */
        readonly AccentTokens: {
            /** Danger */
            readonly danger: string;
            /** On Primary */
            readonly on_primary: string;
            /** Premove */
            readonly premove: string;
            /** Primary */
            readonly primary: string;
            /** Success */
            readonly success: string;
        };
        /** AlphabetPreset */
        readonly AlphabetPreset: {
            /** Classes */
            readonly classes: readonly components["schemas"]["LetterClass"][];
            /** Dictionaries */
            readonly dictionaries: readonly components["schemas"]["DictionaryName"][];
            /** Name */
            readonly name: string;
            /** Order */
            readonly order: readonly string[];
        };
        /**
         * Aspect
         * @enum {string}
         */
        readonly Aspect: "dokonany" | "niedokonany";
        /** Board */
        readonly Board: {
            /** Bonuses */
            readonly bonuses: readonly (components["schemas"]["Bonus"] | null)[];
            /** Size */
            readonly size: number;
            /** Tiles */
            readonly tiles: readonly (components["schemas"]["Tile"] | null)[];
        };
        /** BoardPreset */
        readonly BoardPreset: {
            /** Bonuses */
            readonly bonuses: readonly components["schemas"]["BonusSpec"][];
            /** Name */
            readonly name: string;
            /** Size */
            readonly size: number;
        };
        /** BoardTokens */
        readonly BoardTokens: {
            /** Frame */
            readonly frame: string;
            /** Grid */
            readonly grid: string;
            /** Premium Label Share */
            readonly premium_label_share: number;
            /** Star */
            readonly star: string;
            /** Surface */
            readonly surface: string;
        };
        /** Bonus */
        readonly Bonus: {
            /** Category */
            readonly category?: string | null;
            readonly kind: components["schemas"]["BonusKind"];
            /** Multiplier */
            readonly multiplier: number;
        };
        /**
         * BonusKind
         * @enum {string}
         */
        readonly BonusKind: "word_multiplier" | "letter_multiplier" | "category_multiplier";
        /** BonusSpec */
        readonly BonusSpec: {
            /** Category */
            readonly category?: string | null;
            readonly kind: components["schemas"]["BonusKind"];
            /** Multiplier */
            readonly multiplier: number;
            /** Positions */
            readonly positions: readonly (readonly [
                number,
                number
            ])[];
        };
        /**
         * Case
         * @enum {string}
         */
        readonly Case: "mianownik" | "dopełniacz" | "celownik" | "biernik" | "narzędnik" | "miejscownik" | "wołacz";
        /** ChromeTokens */
        readonly ChromeTokens: {
            /** Edge */
            readonly edge: string;
            /** Muted */
            readonly muted: string;
            /** Panel */
            readonly panel: string;
            /** Surface */
            readonly surface: string;
            /** Text */
            readonly text: string;
        };
        /** ClockView */
        readonly ClockView: {
            /** Deadline */
            readonly deadline: number;
            /** Remaining */
            readonly remaining: {
                readonly [key: string]: number;
            };
            /** Seat */
            readonly seat: number;
            /** Server Time */
            readonly server_time: number;
        };
        /** CompanyView */
        readonly CompanyView: {
            /** Seats */
            readonly seats: readonly components["schemas"]["SeatView"][];
        };
        /**
         * Degree
         * @enum {string}
         */
        readonly Degree: "równy" | "wyższy" | "najwyższy";
        /**
         * DictionaryName
         * @enum {string}
         */
        readonly DictionaryName: "sjp" | "osps" | "english";
        /** DistributionPreset */
        readonly DistributionPreset: {
            /** Counts */
            readonly counts: {
                readonly [key: string]: readonly string[];
            };
            /** Name */
            readonly name: string;
        };
        /**
         * EntryKind
         * @enum {string}
         */
        readonly EntryKind: "move" | "premove_set" | "premove_cleared" | "premove_discarded" | "abandoned";
        /** ErrorBody */
        readonly ErrorBody: {
            readonly code: components["schemas"]["ErrorCode"];
            /** Detail */
            readonly detail: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        readonly ErrorCode: "illegal_move" | "not_your_turn" | "stale_position" | "invalid_word" | "game_over" | "no_premove" | "out_of_time" | "invalid_configuration" | "rejected" | "unknown_table" | "table_closed" | "unknown_code" | "unknown_scheme" | "unknown_preset" | "table_full" | "setting_out_of_range" | "rules_inconsistent" | "malformed_request" | "seat_token_mismatch" | "rack_mismatch" | "gathering" | "dictionary_unavailable" | "word_check_unavailable" | "lore_unavailable" | "too_many_words";
        /** EventView */
        readonly EventView: {
            /** Actor */
            readonly actor: number | null;
            readonly kind: components["schemas"]["EntryKind"];
            readonly move: components["schemas"]["Move"] | null;
            readonly position: components["schemas"]["PositionView"];
            readonly reason: components["schemas"]["RejectionCode"] | null;
            /** Seq */
            readonly seq: number;
        };
        /** Exchange */
        readonly Exchange: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "exchange";
            /** Tile Ids */
            readonly tile_ids: readonly number[];
        };
        /** FeedbackOffered */
        readonly FeedbackOffered: {
            /** Lore */
            readonly lore: boolean;
            /** Word Check */
            readonly word_check: boolean;
        };
        /** GameHighlights */
        readonly GameHighlights: {
            readonly best_word: components["schemas"]["WordHighlight"] | null;
            readonly longest_word: components["schemas"]["WordHighlight"] | null;
        };
        /**
         * Gender
         * @enum {string}
         */
        readonly Gender: "męskoosobowy" | "męskozwierzęcy" | "męskorzeczowy" | "żeński" | "nijaki";
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** InflectedForm */
        readonly InflectedForm: {
            /** Playable */
            readonly playable: boolean;
            readonly tags: components["schemas"]["Inflection"];
            /** Text */
            readonly text: string;
        };
        /** Inflection */
        readonly Inflection: {
            /** Aspects */
            readonly aspects: readonly components["schemas"]["Aspect"][];
            /** Cases */
            readonly cases: readonly components["schemas"]["Case"][];
            readonly degree: components["schemas"]["Degree"] | null;
            /** Deprecative */
            readonly deprecative: boolean;
            /** Genders */
            readonly genders: readonly components["schemas"]["Gender"][];
            readonly governed_case: components["schemas"]["Case"] | null;
            readonly mood: components["schemas"]["Mood"] | null;
            /** Negation */
            readonly negation: boolean | null;
            /** Numbers */
            readonly numbers: readonly components["schemas"]["Number"][];
            readonly numeral_type: components["schemas"]["NumeralType"] | null;
            readonly person: components["schemas"]["Person"] | null;
            readonly pronoun_type: components["schemas"]["PronounType"] | null;
            /** Qualities */
            readonly qualities: readonly components["schemas"]["Quality"][];
            readonly tense: components["schemas"]["Tense"] | null;
            readonly verb_form: components["schemas"]["VerbForm"] | null;
        };
        /** JoinCodeShape */
        readonly JoinCodeShape: {
            /** Alphabet */
            readonly alphabet: string;
            /** Length */
            readonly length: number;
        };
        /** JoinRequest */
        readonly JoinRequest: {
            /** Name */
            readonly name: string;
        };
        /** Letter */
        readonly Letter: {
            /** Category */
            readonly category: string;
            /** Symbol */
            readonly symbol: string;
            /** Value */
            readonly value: number;
        };
        /** LetterAdjustment */
        readonly LetterAdjustment: {
            /** Category */
            readonly category?: string | null;
            /** Count */
            readonly count?: number | null;
            /** Value */
            readonly value?: number | null;
        };
        /** LetterClass */
        readonly LetterClass: {
            /**
             * Category
             * @default standard
             */
            readonly category: string;
            /** Letters */
            readonly letters: readonly string[];
            /** Value */
            readonly value: number;
        };
        /** LoreReading */
        readonly LoreReading: {
            /** Base */
            readonly base: string;
            /** Forms */
            readonly forms: readonly components["schemas"]["InflectedForm"][];
            /** Lexeme */
            readonly lexeme: string;
            readonly part: components["schemas"]["PartOfSpeech"];
        };
        /**
         * Mood
         * @enum {string}
         */
        readonly Mood: "oznajmujący" | "rozkazujący" | "przypuszczający";
        /** Move */
        readonly Move: {
            /** Action */
            readonly action: components["schemas"]["Play"] | components["schemas"]["Exchange"] | components["schemas"]["Pass"];
            /** Player */
            readonly player: number;
        };
        /** MoveAccepted */
        readonly MoveAccepted: {
            /** Seq */
            readonly seq: number;
        };
        /** MoveRequest */
        readonly MoveRequest: {
            /** Base Seq */
            readonly base_seq: number;
            readonly move: components["schemas"]["Move"];
            /**
             * Premove
             * @default false
             */
            readonly premove: boolean;
        };
        /**
         * Number
         * @enum {string}
         */
        readonly Number: "pojedyncza" | "mnoga";
        /**
         * NumeralType
         * @enum {string}
         */
        readonly NumeralType: "główny" | "zbiorowy";
        /** Offering */
        readonly Offering: {
            /** Name */
            readonly name: string;
            readonly rules: components["schemas"]["RulesConfig"];
            /** Specimen */
            readonly specimen: string;
        };
        /** OfferingsResponse */
        readonly OfferingsResponse: {
            /** Allowances */
            readonly allowances: readonly components["schemas"]["SettingAllowance"][];
            readonly code: components["schemas"]["JoinCodeShape"];
            /** Offerings */
            readonly offerings: readonly components["schemas"]["Offering"][];
        };
        /**
         * PartOfSpeech
         * @enum {string}
         */
        readonly PartOfSpeech: "rzeczownik" | "przymiotnik" | "czasownik" | "przysłówek" | "liczebnik" | "zaimek" | "przyimek" | "spójnik" | "partykuła" | "wykrzyknik" | "inny";
        /** Pass */
        readonly Pass: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "pass";
        };
        /**
         * Person
         * @enum {string}
         */
        readonly Person: "pierwsza" | "druga" | "trzecia";
        /**
         * Phase
         * @enum {string}
         */
        readonly Phase: "turn" | "game_over" | "unresolved";
        /** Play */
        readonly Play: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly kind: "play";
            /** Placements */
            readonly placements: readonly components["schemas"]["PlayPlacement"][];
        };
        /** PlayPlacement */
        readonly PlayPlacement: {
            /** Column */
            readonly column: number;
            /** Letter */
            readonly letter?: string | null;
            /** Row */
            readonly row: number;
            /** Tile Id */
            readonly tile_id: number;
        };
        /** PlayRecord */
        readonly PlayRecord: {
            /** Bingo */
            readonly bingo: number;
            /** Indices */
            readonly indices: readonly number[];
            /** Player */
            readonly player: number;
            /** Points */
            readonly points: number;
            /** Turn Number */
            readonly turn_number: number;
            /** Words */
            readonly words: readonly components["schemas"]["ScoredWord"][];
        };
        /** PositionView */
        readonly PositionView: {
            /** Bag Count */
            readonly bag_count: number;
            readonly board: components["schemas"]["Board"];
            /** Consecutive Passes */
            readonly consecutive_passes: number;
            /** Exchange Counts */
            readonly exchange_counts: {
                readonly [key: string]: number;
            };
            readonly last_play: components["schemas"]["PlayRecord"] | null;
            /** Pending Premoves */
            readonly pending_premoves: readonly number[];
            readonly phase: components["schemas"]["Phase"];
            /** Players */
            readonly players: readonly number[];
            readonly premove: components["schemas"]["Move"] | null;
            /** Racks */
            readonly racks: {
                readonly [key: string]: readonly components["schemas"]["Tile"][] | null;
            };
            /** Scoreless Turns */
            readonly scoreless_turns: number;
            /** Scores */
            readonly scores: {
                readonly [key: string]: number;
            };
            /** To Act */
            readonly to_act: readonly number[];
            /** Turn Number */
            readonly turn_number: number;
        };
        /** PremiumTokens */
        readonly PremiumTokens: {
            /** Fill */
            readonly fill: string;
            /** Label */
            readonly label: string;
        };
        /** PresetsResponse */
        readonly PresetsResponse: {
            /** Alphabets */
            readonly alphabets: readonly components["schemas"]["AlphabetPreset"][];
            /** Boards */
            readonly boards: readonly components["schemas"]["BoardPreset"][];
            /** Distributions */
            readonly distributions: readonly components["schemas"]["DistributionPreset"][];
        };
        /**
         * PronounType
         * @enum {string}
         */
        readonly PronounType: "osobowy" | "zwrotny";
        /**
         * Quality
         * @enum {string}
         */
        readonly Quality: "akcentowany" | "nieakcentowany" | "poprzyimkowy" | "niepoprzyimkowy" | "aglutynacyjny" | "nieaglutynacyjny" | "wokaliczny" | "niewokaliczny" | "uzgadniający" | "rządzący" | "zbiorowy" | "niezbiorowy" | "plurale tantum" | "kropkowany" | "niekropkowany" | "złożony";
        /** RackRequest */
        readonly RackRequest: {
            /** Tile Ids */
            readonly tile_ids: readonly number[];
        };
        /**
         * RejectionCode
         * @enum {string}
         */
        readonly RejectionCode: "illegal_move" | "not_your_turn" | "stale_position" | "invalid_word" | "game_over" | "no_premove" | "out_of_time" | "invalid_configuration" | "rejected";
        /** RulesConfig */
        readonly RulesConfig: {
            /** Alphabet */
            readonly alphabet: string;
            /** Bingo Bonus */
            readonly bingo_bonus: number;
            /** Bingo Tiles */
            readonly bingo_tiles: number | null;
            /** Blanks */
            readonly blanks: number;
            /** Board */
            readonly board: string;
            readonly dictionary: components["schemas"]["DictionaryName"];
            /** Distribution */
            readonly distribution: string;
            /** Exchange Limit */
            readonly exchange_limit: number | null;
            /** Exchange Min Bag */
            readonly exchange_min_bag: number;
            /** Going Out Award */
            readonly going_out_award: boolean;
            /** Increment Seconds */
            readonly increment_seconds: number;
            /** Letters */
            readonly letters: {
                readonly [key: string]: components["schemas"]["LetterAdjustment"];
            };
            /** Opening Covers Center */
            readonly opening_covers_center: boolean;
            /** Opening Tiles */
            readonly opening_tiles: number;
            /** Pass Allowed */
            readonly pass_allowed: boolean;
            /** Pass End Rounds */
            readonly pass_end_rounds: number | null;
            /** Per Turn Seconds */
            readonly per_turn_seconds: number | null;
            /** Premoves */
            readonly premoves: boolean;
            /** Rack Size */
            readonly rack_size: number | null;
            /** Scoreless End Limit */
            readonly scoreless_end_limit: number | null;
            /** Seats */
            readonly seats: number;
            /** Total Seconds */
            readonly total_seconds: number | null;
            /** Validate On Play */
            readonly validate_on_play: boolean;
        };
        /** ScoredWord */
        readonly ScoredWord: {
            /** Points */
            readonly points: number;
            /** Text */
            readonly text: string;
        };
        /** SeatView */
        readonly SeatView: {
            /** Claimed */
            readonly claimed: boolean;
            /** Connected */
            readonly connected: boolean;
            /** Name */
            readonly name: string | null;
            /** Seat */
            readonly seat: number;
        };
        /** SettingAllowance */
        readonly SettingAllowance: {
            /** Choices */
            readonly choices: readonly string[] | null;
            readonly group: components["schemas"]["SettingGroup"];
            readonly kind: components["schemas"]["SettingKind"];
            /** Maximum */
            readonly maximum: number | null;
            /** Minimum */
            readonly minimum: number | null;
            /** Offered */
            readonly offered: readonly number[] | null;
            readonly setting: components["schemas"]["SettingName"];
            /** Step */
            readonly step: number | null;
            readonly tier: components["schemas"]["SettingTier"];
            /** Unlimited */
            readonly unlimited: boolean;
        };
        /**
         * SettingGroup
         * @enum {string}
         */
        readonly SettingGroup: "table" | "words" | "turns" | "scoring" | "letters";
        /**
         * SettingKind
         * @enum {string}
         */
        readonly SettingKind: "toggle" | "count" | "optional_count" | "choice" | "seconds" | "letters";
        /**
         * SettingName
         * @enum {string}
         */
        readonly SettingName: "board" | "alphabet" | "distribution" | "dictionary" | "seats" | "rack_size" | "blanks" | "validate_on_play" | "premoves" | "pass_allowed" | "exchange_limit" | "exchange_min_bag" | "opening_tiles" | "opening_covers_center" | "bingo_bonus" | "bingo_tiles" | "going_out_award" | "pass_end_rounds" | "scoreless_end_limit" | "per_turn_seconds" | "total_seconds" | "increment_seconds" | "letters";
        /**
         * SettingTier
         * @enum {string}
         */
        readonly SettingTier: "basic" | "common" | "expert";
        /** StyleTokens */
        readonly StyleTokens: {
            readonly dark: components["schemas"]["ThemeTokens"];
            /** Font Family */
            readonly font_family: string;
            readonly light: components["schemas"]["ThemeTokens"];
            /** Name */
            readonly name: string;
        };
        /** TableAdmission */
        readonly TableAdmission: {
            /** Code */
            readonly code: string;
            /** Name */
            readonly name: string | null;
            /** Scheme */
            readonly scheme: string;
            /** Seat */
            readonly seat: number;
            /** Seats */
            readonly seats: number;
            /** Table Id */
            readonly table_id: string;
            /** Token */
            readonly token: string;
        };
        /** TableDescription */
        readonly TableDescription: {
            /** Alphabet */
            readonly alphabet: readonly components["schemas"]["Letter"][];
            /** Blanks */
            readonly blanks: number;
            /** Code */
            readonly code: string | null;
            /** Distribution */
            readonly distribution: {
                readonly [key: string]: number;
            };
            readonly feedback: components["schemas"]["FeedbackOffered"];
            readonly rules: components["schemas"]["RulesConfig"];
            /** Scheme */
            readonly scheme: string;
            /** Specimen */
            readonly specimen: string;
        };
        /** TableRequest */
        readonly TableRequest: {
            /** Name */
            readonly name: string;
            readonly rules?: components["schemas"]["RulesConfig"] | null;
            /** Scheme */
            readonly scheme: string;
        };
        /** TableViewResponse */
        readonly TableViewResponse: {
            readonly clock: components["schemas"]["ClockView"] | null;
            readonly company: components["schemas"]["CompanyView"];
            /** Seq */
            readonly seq: number;
            readonly view: components["schemas"]["PositionView"];
        };
        /**
         * Tense
         * @enum {string}
         */
        readonly Tense: "teraźniejszy" | "przeszły" | "przyszły";
        /** ThemeTokens */
        readonly ThemeTokens: {
            readonly accents: components["schemas"]["AccentTokens"];
            readonly board: components["schemas"]["BoardTokens"];
            /** Category Premiums */
            readonly category_premiums: {
                readonly [key: string]: components["schemas"]["PremiumTokens"];
            };
            readonly chrome: components["schemas"]["ChromeTokens"];
            /** Premiums */
            readonly premiums: {
                readonly [key: string]: components["schemas"]["PremiumTokens"];
            };
            readonly tiles: components["schemas"]["TileTokens"];
        };
        /** Tile */
        readonly Tile: {
            /** Blank */
            readonly blank: boolean;
            /** Category */
            readonly category: string;
            /** Identifier */
            readonly identifier: number;
            /** Letter */
            readonly letter: string;
            /** Value */
            readonly value: number;
        };
        /** TileTokens */
        readonly TileTokens: {
            /** Bands */
            readonly bands: {
                readonly [key: string]: string;
            };
            /** Edge */
            readonly edge: string;
            /** Face */
            readonly face: string;
            /** Face Tint */
            readonly face_tint: number;
            /** Text */
            readonly text: string;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
        /**
         * VerbForm
         * @enum {string}
         */
        readonly VerbForm: "bezokolicznik" | "forma osobowa" | "forma przeszła" | "forma przypuszczająca" | "rozkaźnik" | "bezosobnik" | "imiesłów czynny" | "imiesłów bierny" | "imiesłów współczesny" | "imiesłów uprzedni" | "odsłownik" | "końcówka ruchoma" | "predykatyw" | "winien";
        /** WordHighlight */
        readonly WordHighlight: {
            /** Player */
            readonly player: number;
            /** Points */
            readonly points: number;
            /** Turn Number */
            readonly turn_number: number;
            /** Word */
            readonly word: string;
        };
        /** WordLore */
        readonly WordLore: {
            /** Playable */
            readonly playable: boolean;
            /** Readings */
            readonly readings: readonly components["schemas"]["LoreReading"][];
            /** Word */
            readonly word: string;
        };
        /** WordLoreResponse */
        readonly WordLoreResponse: {
            /** Lore */
            readonly lore: {
                readonly [key: string]: components["schemas"]["WordLore"];
            };
        };
        /** WordVerdict */
        readonly WordVerdict: {
            /** Allowed */
            readonly allowed: boolean;
            /** Reason */
            readonly reason?: string | null;
        };
        /** WordVerdicts */
        readonly WordVerdicts: {
            /** Verdicts */
            readonly verdicts: {
                readonly [key: string]: components["schemas"]["WordVerdict"];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly serve_index__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": unknown;
                };
            };
        };
    };
    readonly read_invitation_invitations__code__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly code: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TableDescription"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_offerings_offerings_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OfferingsResponse"];
                };
            };
        };
    };
    readonly list_offered_presets_presets_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PresetsResponse"];
                };
            };
        };
    };
    readonly read_style_style_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StyleTokens"];
                };
            };
        };
    };
    readonly create_table_tables_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["TableRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TableAdmission"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    readonly join_table_tables__code__join_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly code: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["JoinRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TableAdmission"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly describe_table_tables__table_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TableDescription"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly stream_events_tables__table_id__events_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "Last-Event-ID"?: string | null;
            };
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["EventView"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly table_highlights_tables__table_id__highlights_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GameHighlights"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly read_lore_tables__table_id__lore_get: {
        readonly parameters: {
            readonly query: {
                readonly words: readonly string[];
            };
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WordLoreResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    readonly submit_move_tables__table_id__moves_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["MoveRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MoveAccepted"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly cancel_premove_tables__table_id__premove_delete: {
        readonly parameters: {
            readonly query: {
                readonly base_seq: number;
            };
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MoveAccepted"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly arrange_rack_tables__table_id__rack_put: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["RackRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            readonly 409: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly table_view_tables__table_id__view_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TableViewResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly judge_words_tables__table_id__words_get: {
        readonly parameters: {
            readonly query: {
                readonly words: readonly string[];
            };
            readonly header?: never;
            readonly path: {
                readonly table_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WordVerdicts"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Gone */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
