/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Index */
        get: operations["serve_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offerings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Offerings */
        get: operations["list_offerings_offerings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Style */
        get: operations["read_style_style_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Table */
        post: operations["create_table_tables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{code}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Table */
        post: operations["join_table_tables__code__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe Table */
        get: operations["describe_table_tables__table_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_tables__table_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Move */
        post: operations["submit_move_tables__table_id__moves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/premove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Premove */
        delete: operations["cancel_premove_tables__table_id__premove_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Table View */
        get: operations["table_view_tables__table_id__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{table_id}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Judge Words */
        get: operations["judge_words_tables__table_id__words_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccentTokens */
        AccentTokens: {
            /** Danger */
            danger: string;
            /** On Primary */
            on_primary: string;
            /** Premove */
            premove: string;
            /** Primary */
            primary: string;
            /** Success */
            success: string;
        };
        /** Board */
        Board: {
            /** Bonuses */
            bonuses: (components["schemas"]["Bonus"] | null)[];
            /** Size */
            size: number;
            /** Tiles */
            tiles: (components["schemas"]["Tile"] | null)[];
        };
        /** BoardTokens */
        BoardTokens: {
            /** Frame */
            frame: string;
            /** Grid */
            grid: string;
            /** Premium Label Share */
            premium_label_share: number;
            /** Star */
            star: string;
            /** Surface */
            surface: string;
        };
        /** Bonus */
        Bonus: {
            /** Category */
            category?: string | null;
            kind: components["schemas"]["BonusKind"];
            /** Multiplier */
            multiplier: number;
        };
        /**
         * BonusKind
         * @enum {string}
         */
        BonusKind: "word_multiplier" | "letter_multiplier" | "category_multiplier";
        /** ChromeTokens */
        ChromeTokens: {
            /** Edge */
            edge: string;
            /** Muted */
            muted: string;
            /** Panel */
            panel: string;
            /** Surface */
            surface: string;
            /** Text */
            text: string;
        };
        /** ClockView */
        ClockView: {
            /** Deadline */
            deadline: number;
            /** Remaining */
            remaining: {
                [key: string]: number;
            };
            /** Seat */
            seat: number;
            /** Server Time */
            server_time: number;
        };
        /** CompanyView */
        CompanyView: {
            /** Seats */
            seats: components["schemas"]["SeatView"][];
        };
        /**
         * DictionaryName
         * @enum {string}
         */
        DictionaryName: "sjp" | "osps" | "english";
        /**
         * EntryKind
         * @enum {string}
         */
        EntryKind: "move" | "premove_set" | "premove_cleared" | "premove_discarded";
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "illegal_move" | "not_your_turn" | "stale_position" | "invalid_word" | "game_over" | "no_premove" | "invalid_configuration" | "rejected" | "unknown_table" | "unknown_code" | "unknown_scheme" | "table_full" | "seats_out_of_range" | "seat_token_mismatch" | "gathering" | "dictionary_unavailable" | "word_check_unavailable" | "too_many_words";
        /** EventView */
        EventView: {
            /** Actor */
            actor: number | null;
            kind: components["schemas"]["EntryKind"];
            move: components["schemas"]["Move"] | null;
            position: components["schemas"]["PositionView"];
            reason: components["schemas"]["RejectionCode"] | null;
            /** Seq */
            seq: number;
        };
        /** Exchange */
        Exchange: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "exchange";
            /** Tile Ids */
            tile_ids: number[];
        };
        /**
         * GameName
         * @enum {string}
         */
        GameName: "literaki" | "scrabble";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JoinRequest */
        JoinRequest: {
            /** Name */
            name: string;
        };
        /** Letter */
        Letter: {
            /** Category */
            category: string;
            /** Symbol */
            symbol: string;
            /** Value */
            value: number;
        };
        /** Move */
        Move: {
            /** Action */
            action: components["schemas"]["Play"] | components["schemas"]["Exchange"] | components["schemas"]["Pass"] | components["schemas"]["Reorder"];
            /** Player */
            player: number;
        };
        /** MoveAccepted */
        MoveAccepted: {
            /** Seq */
            seq: number;
        };
        /** MoveRequest */
        MoveRequest: {
            /** Base Seq */
            base_seq: number;
            move: components["schemas"]["Move"];
            /**
             * Premove
             * @default false
             */
            premove: boolean;
        };
        /** Offering */
        Offering: {
            dictionary: components["schemas"]["DictionaryName"];
            game: components["schemas"]["GameName"];
            /** Max Players */
            max_players: number;
            /** Min Players */
            min_players: number;
            /** Name */
            name: string;
        };
        /** OfferingsResponse */
        OfferingsResponse: {
            /** Offerings */
            offerings: components["schemas"]["Offering"][];
        };
        /** Pass */
        Pass: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pass";
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "turn" | "game_over";
        /** Play */
        Play: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "play";
            /** Placements */
            placements: components["schemas"]["PlayPlacement"][];
        };
        /** PlayPlacement */
        PlayPlacement: {
            /** Column */
            column: number;
            /** Letter */
            letter?: string | null;
            /** Row */
            row: number;
            /** Tile Id */
            tile_id: number;
        };
        /** PlayRecord */
        PlayRecord: {
            /** Bingo */
            bingo: number;
            /** Indices */
            indices: number[];
            /** Player */
            player: number;
            /** Points */
            points: number;
            /** Turn Number */
            turn_number: number;
            /** Words */
            words: components["schemas"]["ScoredWord"][];
        };
        /** PositionView */
        PositionView: {
            /** Bag Count */
            bag_count: number;
            board: components["schemas"]["Board"];
            /** Consecutive Passes */
            consecutive_passes: number;
            /** Exchange Counts */
            exchange_counts: {
                [key: string]: number;
            };
            last_play: components["schemas"]["PlayRecord"] | null;
            /** Pending Premoves */
            pending_premoves: number[];
            phase: components["schemas"]["Phase"];
            /** Players */
            players: number[];
            premove: components["schemas"]["Move"] | null;
            /** Racks */
            racks: {
                [key: string]: components["schemas"]["Tile"][] | null;
            };
            /** Scoreless Turns */
            scoreless_turns: number;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** To Act */
            to_act: number[];
            /** Turn Number */
            turn_number: number;
        };
        /** PremiumTokens */
        PremiumTokens: {
            /** Fill */
            fill: string;
            /** Label */
            label: string;
        };
        /**
         * RejectionCode
         * @enum {string}
         */
        RejectionCode: "illegal_move" | "not_your_turn" | "stale_position" | "invalid_word" | "game_over" | "no_premove" | "invalid_configuration" | "rejected";
        /** Reorder */
        Reorder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reorder";
            /** Tile Ids */
            tile_ids: number[];
        };
        /** RuleParameters */
        RuleParameters: {
            /** Bingo Bonus */
            bingo_bonus: number;
            /** Exchange Limit */
            exchange_limit: number | null;
            /** Exchange Min Bag */
            exchange_min_bag: number;
            /** Pass Allowed */
            pass_allowed: boolean;
            /** Pass End Limit */
            pass_end_limit: number | null;
            /** Premoves Allowed */
            premoves_allowed: boolean;
            /** Rack Size */
            rack_size: number | null;
            /** Scoreless End Limit */
            scoreless_end_limit: number | null;
            time: components["schemas"]["TimeConfig"];
            /** Validate On Play */
            validate_on_play: boolean;
            /** Word Check */
            word_check: boolean;
        };
        /** ScoredWord */
        ScoredWord: {
            /** Points */
            points: number;
            /** Text */
            text: string;
        };
        /** SeatView */
        SeatView: {
            /** Claimed */
            claimed: boolean;
            /** Connected */
            connected: boolean;
            /** Name */
            name: string | null;
            /** Seat */
            seat: number;
        };
        /** StyleTokens */
        StyleTokens: {
            dark: components["schemas"]["ThemeTokens"];
            /** Font Family */
            font_family: string;
            light: components["schemas"]["ThemeTokens"];
            /** Name */
            name: string;
        };
        /** TableAdmission */
        TableAdmission: {
            /** Code */
            code: string;
            game: components["schemas"]["GameName"];
            /** Max Players */
            max_players: number;
            /** Name */
            name: string | null;
            /** Scheme */
            scheme: string;
            /** Seat */
            seat: number;
            /** Table Id */
            table_id: string;
            /** Token */
            token: string;
        };
        /** TableDescription */
        TableDescription: {
            /** Alphabet */
            alphabet: components["schemas"]["Letter"][];
            /** Blanks */
            blanks: number;
            /** Code */
            code: string | null;
            dictionary: components["schemas"]["DictionaryName"];
            /** Distribution */
            distribution: {
                [key: string]: number;
            };
            game: components["schemas"]["GameName"];
            parameters: components["schemas"]["RuleParameters"];
            /** Scheme */
            scheme: string;
            /** Seats */
            seats: number;
        };
        /** TableRequest */
        TableRequest: {
            /** Name */
            name: string;
            /** Scheme */
            scheme: string;
            /** Seats */
            seats: number;
            time?: components["schemas"]["TableTimeRequest"] | null;
        };
        /** TableTimeRequest */
        TableTimeRequest: {
            /**
             * Increment Seconds
             * @default 0
             */
            increment_seconds: number;
            /** Total Seconds */
            total_seconds?: number | null;
        };
        /** TableViewResponse */
        TableViewResponse: {
            clock: components["schemas"]["ClockView"] | null;
            company: components["schemas"]["CompanyView"];
            /** Seq */
            seq: number;
            view: components["schemas"]["PositionView"];
        };
        /** ThemeTokens */
        ThemeTokens: {
            accents: components["schemas"]["AccentTokens"];
            board: components["schemas"]["BoardTokens"];
            /** Category Premiums */
            category_premiums: {
                [key: string]: components["schemas"]["PremiumTokens"];
            };
            chrome: components["schemas"]["ChromeTokens"];
            /** Premiums */
            premiums: {
                [key: string]: components["schemas"]["PremiumTokens"];
            };
            tiles: components["schemas"]["TileTokens"];
        };
        /** Tile */
        Tile: {
            /** Blank */
            blank: boolean;
            /** Category */
            category: string;
            /** Identifier */
            identifier: number;
            /** Letter */
            letter: string;
            /** Value */
            value: number;
        };
        /** TileTokens */
        TileTokens: {
            /** Bands */
            bands: {
                [key: string]: string;
            };
            /** Edge */
            edge: string;
            /** Face */
            face: string;
            /** Face Tint */
            face_tint: number;
            /** Text */
            text: string;
        };
        /** TimeConfig */
        TimeConfig: {
            /** Increment Seconds */
            increment_seconds: number;
            /** Per Turn Seconds */
            per_turn_seconds: number | null;
            /** Total Seconds */
            total_seconds: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WordVerdict */
        WordVerdict: {
            /** Allowed */
            allowed: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** WordVerdicts */
        WordVerdicts: {
            /** Verdicts */
            verdicts: {
                [key: string]: components["schemas"]["WordVerdict"];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    serve_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_offerings_offerings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferingsResponse"];
                };
            };
        };
    };
    read_style_style_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleTokens"];
                };
            };
        };
    };
    create_table_tables_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableAdmission"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    join_table_tables__code__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableAdmission"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    describe_table_tables__table_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDescription"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_tables__table_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_move_tables__table_id__moves_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_premove_tables__table_id__premove_delete: {
        parameters: {
            query: {
                base_seq: number;
            };
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_view_tables__table_id__view_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableViewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    judge_words_tables__table_id__words_get: {
        parameters: {
            query: {
                words: string[];
            };
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordVerdicts"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
