// Generated by scripts/strings.py from config/strings. Edits are overwritten.

export type Locale = "en" | "pl";

export const LOCALES: readonly Locale[] = ["en", "pl"];

export const DEFAULT_LOCALE: Locale = "en";

export type PluralCategory = "few" | "many" | "one" | "other";

export type EmptyValues = Record<never, never>;

export interface PlainValues {
    readonly "arrive.code_label": EmptyValues;
    readonly "arrive.copied_mark": EmptyValues;
    readonly "arrive.copy_code_label": EmptyValues;
    readonly "arrive.create_button": EmptyValues;
    readonly "arrive.create_heading": EmptyValues;
    readonly "arrive.increment_label": EmptyValues;
    readonly "arrive.invite_button": EmptyValues;
    readonly "arrive.invite_copied": EmptyValues;
    readonly "arrive.join_button": EmptyValues;
    readonly "arrive.join_heading": EmptyValues;
    readonly "arrive.joining": EmptyValues;
    readonly "arrive.name_label": EmptyValues;
    readonly "arrive.name_placeholder": EmptyValues;
    readonly "arrive.offerings_loading": EmptyValues;
    readonly "arrive.scheme_label": EmptyValues;
    readonly "arrive.seats_label": EmptyValues;
    readonly "arrive.span": { readonly maximum: number; readonly minimum: number };
    readonly "arrive.stale_notice": EmptyValues;
    readonly "arrive.switch_to_create": EmptyValues;
    readonly "arrive.switch_to_join": EmptyValues;
    readonly "arrive.time_label": EmptyValues;
    readonly "arrive.untimed": EmptyValues;
    readonly "board.label": EmptyValues;
    readonly "board.square": { readonly column: number; readonly row: number };
    readonly "clock.budget": { readonly minutes: number };
    readonly "clock.empty": EmptyValues;
    readonly "clock.increment": { readonly seconds: number };
    readonly "clock.increment_none": EmptyValues;
    readonly "clock.time": { readonly minutes: number; readonly seconds: string };
    readonly "connection.joining": EmptyValues;
    readonly "connection.live": EmptyValues;
    readonly "connection.lost": EmptyValues;
    readonly "connection.resuming": EmptyValues;
    readonly "docket.bag": { readonly tiles: number };
    readonly "docket.blank_row_mark": EmptyValues;
    readonly "docket.log_exchange": EmptyValues;
    readonly "docket.log_label": EmptyValues;
    readonly "docket.log_pass": EmptyValues;
    readonly "docket.log_play": { readonly points: number; readonly words: string };
    readonly "docket.log_premove_returned": EmptyValues;
    readonly "docket.log_premove_returned_reason": { readonly reason: string };
    readonly "docket.premove_returned": EmptyValues;
    readonly "docket.premove_returned_reason": { readonly reason: string };
    readonly "docket.remaining_label": EmptyValues;
    readonly "general.list_pair": { readonly last: string; readonly leading: string };
    readonly "general.list_separator": EmptyValues;
    readonly "guidance.detached": EmptyValues;
    readonly "guidance.gapped": EmptyValues;
    readonly "guidance.off_center": EmptyValues;
    readonly "guidance.opening_short": EmptyValues;
    readonly "guidance.place": EmptyValues;
    readonly "guidance.scattered": EmptyValues;
    readonly "hand.bingo": { readonly bonus: number };
    readonly "hand.blank_tile": EmptyValues;
    readonly "hand.cancel_premove": EmptyValues;
    readonly "hand.exchange_bag_low": { readonly minimum: number };
    readonly "hand.exchange_button": { readonly tiles: number };
    readonly "hand.exchange_hint": EmptyValues;
    readonly "hand.exchange_queued": EmptyValues;
    readonly "hand.exchange_spent": EmptyValues;
    readonly "hand.park_here": EmptyValues;
    readonly "hand.pass_button": EmptyValues;
    readonly "hand.play_button": EmptyValues;
    readonly "hand.premove_button": EmptyValues;
    readonly "hand.premove_queued": EmptyValues;
    readonly "hand.primary_scored": { readonly action: string; readonly points: number };
    readonly "hand.rack_label": EmptyValues;
    readonly "hand.recall_button": EmptyValues;
    readonly "hand.return_here": EmptyValues;
    readonly "hand.shuffle_button": EmptyValues;
    readonly "hand.tile": { readonly letter: string; readonly value: number };
    readonly "hand.tray_hint": EmptyValues;
    readonly "hand.tray_label": EmptyValues;
    readonly "product.name": EmptyValues;
    readonly "product.style_fallback": EmptyValues;
    readonly "product.tagline": EmptyValues;
    readonly "seats.fallback_name": { readonly seat: number };
    readonly "seats.gathering": { readonly present: number; readonly total: number };
    readonly "seats.locale_caption": EmptyValues;
    readonly "seats.locale_label": EmptyValues;
    readonly "seats.mode_dark": EmptyValues;
    readonly "seats.mode_label": EmptyValues;
    readonly "seats.mode_light": EmptyValues;
    readonly "seats.mode_system": EmptyValues;
    readonly "seats.notice_label": EmptyValues;
    readonly "seats.notice_off": EmptyValues;
    readonly "seats.notice_on": EmptyValues;
    readonly "seats.open_seat": EmptyValues;
    readonly "seats.players_label": EmptyValues;
    readonly "seats.waiting": EmptyValues;
    readonly "seats.you_marker": EmptyValues;
    readonly "seats.your_turn": EmptyValues;
    readonly "sheets.blank_close": EmptyValues;
    readonly "sheets.blank_confirm": EmptyValues;
    readonly "sheets.blank_heading": EmptyValues;
    readonly "sheets.blank_input_label": EmptyValues;
    readonly "sheets.game_over_heading": EmptyValues;
    readonly "words.absent": EmptyValues;
    readonly "words.asking": EmptyValues;
    readonly "words.deepen": EmptyValues;
    readonly "words.failed": EmptyValues;
    readonly "words.label": EmptyValues;
    readonly "words.panel_close": EmptyValues;
    readonly "words.panel_label": { readonly word: string };
    readonly "words.paradigm_back": EmptyValues;
    readonly "words.paradigm_back_label": EmptyValues;
    readonly "words.paradigm_gap": EmptyValues;
    readonly "words.paradigm_other_forms": EmptyValues;
    readonly "words.paradigm_plain_forms": EmptyValues;
    readonly "words.sample": EmptyValues;
    readonly "words.term_separator": EmptyValues;
    readonly "words.unclassified": EmptyValues;
    readonly "words.unclassified_part": EmptyValues;
    readonly "words.verdict_invalid": EmptyValues;
    readonly "words.verdict_standing": EmptyValues;
    readonly "words.verdict_valid": EmptyValues;
}

export interface PluralValues {
    readonly "arrive.offering": { readonly name: string; readonly span: string };
    readonly "hand.exchange_left": EmptyValues;
    readonly "seats.thinking": { readonly names: string };
    readonly "seats.won": { readonly names: string; readonly points: number };
}

export type PlainKey = keyof PlainValues;

export type PluralKey = keyof PluralValues;

export interface Catalogue {
    readonly plain: Record<PlainKey, string>;
    readonly plural: Record<PluralKey, Record<PluralCategory, string>>;
}
