import json
import re
from collections.abc import Iterator
from pathlib import Path
from typing import Final, NamedTuple

import yaml

from wordcore.errors.exceptions import InvalidConfiguration

PROJECT_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
CATALOG_DIR: Final[Path] = PROJECT_ROOT / "config" / "strings"
OUTPUT_DIR: Final[Path] = PROJECT_ROOT / "frontend" / "src" / "text"

REFERENCE_LOCALE: Final = "en"
PLURAL_MARKER: Final = "plural"
COUNT_NAME: Final = "count"
CATEGORIES: Final = ("one", "few", "many", "other")
CATEGORY_SOURCES: Final[dict[str, dict[str, str]]] = {
    "en": {"one": "one", "few": "other", "many": "other", "other": "other"},
    "pl": {"one": "one", "few": "few", "many": "many", "other": "many"},
}

_BRACED: Final = re.compile(r"\{([^{}]*)\}")
_PLACEHOLDER: Final = re.compile(r"^(?P<name>[a-z_]+)(?P<numeric>:number)?$")
_ANNOTATED: Final = re.compile(r"\{([a-z_]+):number\}")
_BANNER: Final = "// Generated by scripts/strings.py from config/strings. Edits are overwritten."
_INDENT: Final = " " * 4


class Placeholder(NamedTuple):
    name: str
    numeric: bool


class Catalog(NamedTuple):
    plain: dict[str, str]
    plural: dict[str, dict[str, str]]


class Shape(NamedTuple):
    plain: dict[str, tuple[Placeholder, ...]]
    plural: dict[str, tuple[Placeholder, ...]]


def main(directory: Path, output: Path) -> None:
    locales = locale_names(directory)
    authored = {locale: read_catalog(directory / f"{locale}.yaml") for locale in locales}
    shape = shape_of(authored[REFERENCE_LOCALE])
    resolved = {locale: resolved_catalog(locale, authored[locale], shape) for locale in locales}
    sources = {output / "keys.ts": keys_source(locales, shape)} | {
        output / f"{locale}.ts": locale_source(locale, resolved[locale]) for locale in locales
    }
    for path, body in sources.items():
        path.write_text(body, encoding="utf-8")
        print(f"{path}: {len(body)} bytes")


def locale_names(directory: Path) -> tuple[str, ...]:
    names = sorted(path.stem for path in directory.glob("*.yaml"))
    _ensure_reference_present(names)
    return (REFERENCE_LOCALE, *(name for name in names if name != REFERENCE_LOCALE))


def read_catalog(path: Path) -> Catalog:
    plain: dict[str, str] = {}
    plural: dict[str, dict[str, str]] = {}
    for key, message in _messages("", _document(path)):
        if isinstance(message, str):
            plain[key] = message
        else:
            plural[key] = message
    return Catalog(plain=plain, plural=plural)


def shape_of(reference: Catalog) -> Shape:
    plain = {
        key: placeholders_of(key, template, plural=False)
        for key, template in reference.plain.items()
    }
    plural = {
        key: _agreed_placeholders(key, templates) for key, templates in reference.plural.items()
    }
    return Shape(plain=plain, plural=plural)


def resolved_catalog(locale: str, authored: Catalog, shape: Shape) -> Catalog:
    _ensure_locale_known(locale)
    _ensure_same_keys(locale, authored, shape)
    plain = {
        key: _resolved_plain(locale, key, template, shape.plain[key])
        for key, template in authored.plain.items()
    }
    plural = {
        key: _resolved_plural(locale, key, templates, shape.plural[key])
        for key, templates in authored.plural.items()
    }
    return Catalog(plain=plain, plural=plural)


def placeholders_of(key: str, template: str, plural: bool) -> tuple[Placeholder, ...]:
    _ensure_braces_paired(key, template)
    found = {_parsed_placeholder(key, braced.group(1)) for braced in _BRACED.finditer(template)}
    _ensure_count_reserved(key, found, plural=plural)
    return tuple(sorted(found - {Placeholder(name=COUNT_NAME, numeric=True)}))


def keys_source(locales: tuple[str, ...], shape: Shape) -> str:
    lines = [
        _BANNER,
        "",
        f"export type Locale = {_union(locales)};",
        "",
        f"export const LOCALES: readonly Locale[] = [{_listed(locales)}];",
        "",
        f"export const DEFAULT_LOCALE: Locale = {_quoted(REFERENCE_LOCALE)};",
        "",
        f"export type PluralCategory = {_union(tuple(sorted(CATEGORIES)))};",
        "",
        "export type EmptyValues = Record<never, never>;",
        "",
        *_values_interface("PlainValues", shape.plain),
        "",
        *_values_interface("PluralValues", shape.plural),
        "",
        "export type PlainKey = keyof PlainValues;",
        "",
        "export type PluralKey = keyof PluralValues;",
        "",
        "export interface Catalog {",
        f"{_INDENT}readonly plain: Record<PlainKey, string>;",
        f"{_INDENT}readonly plural: Record<PluralKey, Record<PluralCategory, string>>;",
        "}",
    ]
    return "\n".join(lines) + "\n"


def locale_source(locale: str, catalog: Catalog) -> str:
    lines = [
        _BANNER,
        "",
        'import type { Catalog } from "./keys";',
        "",
        f"export const {locale.upper()}: Catalog = {{",
        f"{_INDENT}plain: {{",
        *(
            f"{_INDENT * 2}{_quoted(key)}: {_quoted(catalog.plain[key])},"
            for key in sorted(catalog.plain)
        ),
        f"{_INDENT}}},",
        f"{_INDENT}plural: {{",
        *_plural_entries(catalog.plural),
        f"{_INDENT}}},",
        "};",
    ]
    return "\n".join(lines) + "\n"


def _document(path: Path) -> dict[str, object]:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        raise InvalidConfiguration(f"{path}: expected a mapping of message namespaces")
    return {str(name): value for name, value in loaded.items()}


def _messages(prefix: str, node: dict[str, object]) -> Iterator[tuple[str, str | dict[str, str]]]:
    for name, value in node.items():
        key = f"{prefix}.{name}" if prefix else str(name)
        if isinstance(value, str):
            yield key, value
        elif isinstance(value, dict):
            branch = {str(inner): entry for inner, entry in value.items()}
            categories = _plural_categories(key, branch)
            if categories is None:
                yield from _messages(key, branch)
            else:
                yield key, categories
        else:
            raise InvalidConfiguration(f"{key}: expected a message or a namespace")


def _plural_categories(key: str, node: dict[str, object]) -> dict[str, str] | None:
    if PLURAL_MARKER not in node:
        return None
    _ensure_plural_alone(key, node)
    table = node[PLURAL_MARKER]
    if not isinstance(table, dict):
        raise InvalidConfiguration(f"{key}: expected a mapping of plural categories")
    return {str(category): _text(key, str(category), entry) for category, entry in table.items()}


def _text(key: str, category: str, entry: object) -> str:
    if not isinstance(entry, str):
        raise InvalidConfiguration(f"{key}.{category}: expected a message")
    return entry


def _agreed_placeholders(key: str, templates: dict[str, str]) -> tuple[Placeholder, ...]:
    found = {
        category: placeholders_of(key, template, plural=True)
        for category, template in templates.items()
    }
    _ensure_categories_agree(key, found)
    return next(iter(found.values()), ())


def _resolved_plain(locale: str, key: str, template: str, expected: tuple[Placeholder, ...]) -> str:
    _ensure_filled(locale, key, template)
    _ensure_placeholders_match(locale, key, placeholders_of(key, template, plural=False), expected)
    return _stripped(template)


def _resolved_plural(
    locale: str, key: str, templates: dict[str, str], expected: tuple[Placeholder, ...]
) -> dict[str, str]:
    _ensure_categories_authored(locale, key, templates)
    for category, template in templates.items():
        _ensure_filled(locale, f"{key}.{category}", template)
    _ensure_placeholders_match(locale, key, _agreed_placeholders(key, templates), expected)
    sources = CATEGORY_SOURCES[locale]
    return {category: _stripped(templates[sources[category]]) for category in CATEGORIES}


def _parsed_placeholder(key: str, body: str) -> Placeholder:
    matched = _PLACEHOLDER.match(body)
    if matched is None:
        raise InvalidConfiguration(f"{key}: {{{body}}} is not a placeholder")
    return Placeholder(name=matched.group("name"), numeric=matched.group("numeric") is not None)


def _stripped(template: str) -> str:
    return _ANNOTATED.sub(r"{\1}", template)


def _values_interface(name: str, shape: dict[str, tuple[Placeholder, ...]]) -> list[str]:
    return [
        f"export interface {name} {{",
        *(
            f"{_INDENT}readonly {_quoted(key)}: {_values_type(shape[key])};"
            for key in sorted(shape)
        ),
        "}",
    ]


def _values_type(placeholders: tuple[Placeholder, ...]) -> str:
    if len(placeholders) == 0:
        return "EmptyValues"
    fields = "; ".join(
        f"readonly {placeholder.name}: {'number' if placeholder.numeric else 'string'}"
        for placeholder in placeholders
    )
    return f"{{ {fields} }}"


def _plural_entries(plural: dict[str, dict[str, str]]) -> list[str]:
    lines: list[str] = []
    for key in sorted(plural):
        lines.append(f"{_INDENT * 2}{_quoted(key)}: {{")
        lines.extend(
            f"{_INDENT * 3}{category}: {_quoted(plural[key][category])}," for category in CATEGORIES
        )
        lines.append(f"{_INDENT * 2}}},")
    return lines


def _listed(members: tuple[str, ...]) -> str:
    return ", ".join(_quoted(member) for member in members)


def _union(members: tuple[str, ...]) -> str:
    return " | ".join(_quoted(member) for member in members)


def _quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _ensure_reference_present(names: list[str]) -> None:
    if REFERENCE_LOCALE not in names:
        raise InvalidConfiguration(f"the reference catalog {REFERENCE_LOCALE}.yaml is missing")


def _ensure_locale_known(locale: str) -> None:
    if locale not in CATEGORY_SOURCES:
        raise InvalidConfiguration(f"{locale}: plural categories are undeclared for this locale")


def _ensure_same_keys(locale: str, authored: Catalog, shape: Shape) -> None:
    for kind, present, expected in (
        ("message", set(authored.plain), set(shape.plain)),
        ("plural message", set(authored.plural), set(shape.plural)),
    ):
        missing = sorted(expected - present)
        if len(missing) > 0:
            raise InvalidConfiguration(f"{locale}: {kind} {missing[0]} is missing")
        extra = sorted(present - expected)
        if len(extra) > 0:
            raise InvalidConfiguration(f"{locale}: {kind} {extra[0]} is absent from the reference")


def _ensure_filled(locale: str, key: str, template: str) -> None:
    if len(template.strip()) == 0:
        raise InvalidConfiguration(f"{locale}: {key} carries no message")


def _ensure_braces_paired(key: str, template: str) -> None:
    matched = len(_BRACED.findall(template))
    if template.count("{") != matched or template.count("}") != matched:
        raise InvalidConfiguration(f"{key}: braces are unbalanced")


def _ensure_count_reserved(key: str, found: set[Placeholder], plural: bool) -> None:
    named = {placeholder.name: placeholder for placeholder in found}
    counted = named.get(COUNT_NAME)
    if counted is None:
        return
    if not plural:
        raise InvalidConfiguration(f"{key}: {COUNT_NAME} belongs to plural messages")
    if not counted.numeric:
        raise InvalidConfiguration(f"{key}: {COUNT_NAME} must be declared as a number")


def _ensure_placeholders_match(
    locale: str, key: str, present: tuple[Placeholder, ...], expected: tuple[Placeholder, ...]
) -> None:
    if present != expected:
        raise InvalidConfiguration(
            f"{locale}: {key} carries {_named(present)}"
            f" where the reference carries {_named(expected)}"
        )


def _ensure_plural_alone(key: str, node: dict[str, object]) -> None:
    if len(node) > 1:
        raise InvalidConfiguration(f"{key}: a plural message holds nothing beside its categories")


def _ensure_categories_agree(key: str, found: dict[str, tuple[Placeholder, ...]]) -> None:
    distinct = set(found.values())
    if len(distinct) > 1:
        raise InvalidConfiguration(f"{key}: plural categories carry different placeholders")


def _ensure_categories_authored(locale: str, key: str, templates: dict[str, str]) -> None:
    expected = set(CATEGORY_SOURCES[locale].values())
    if set(templates) != expected:
        raise InvalidConfiguration(f"{locale}: {key} needs the categories {sorted(expected)}")


def _named(placeholders: tuple[Placeholder, ...]) -> str:
    if len(placeholders) == 0:
        return "no placeholders"
    return ", ".join(placeholder.name for placeholder in placeholders)


if __name__ == "__main__":
    main(CATALOG_DIR, OUTPUT_DIR)
