letters:
  - symbol: "A"
    value: 1
    category: yellow
    count: 9
  - symbol: "Ą"
    value: 5
    category: red
    count: 1
  - symbol: "B"
    value: 3
    category: blue
    count: 2
  - symbol: "C"
    value: 2
    category: green
    count: 3
  - symbol: "Ć"
    value: 5
    category: red
    count: 1
  - symbol: "D"
    value: 2
    category: green
    count: 3
  - symbol: "E"
    value: 1
    category: yellow
    count: 7
  - symbol: "Ę"
    value: 5
    category: red
    count: 1
  - symbol: "F"
    value: 5
    category: red
    count: 1
  - symbol: "G"
    value: 3
    category: blue
    count: 2
  - symbol: "H"
    value: 3
    category: blue
    count: 2
  - symbol: "I"
    value: 1
    category: yellow
    count: 8
  - symbol: "J"
    value: 3
    category: blue
    count: 2
  - symbol: "K"
    value: 2
    category: green
    count: 3
  - symbol: "L"
    value: 2
    category: green
    count: 3
  - symbol: "Ł"
    value: 3
    category: blue
    count: 2
  - symbol: "M"
    value: 2
    category: green
    count: 3
  - symbol: "N"
    value: 1
    category: yellow
    count: 5
  - symbol: "Ń"
    value: 5
    category: red
    count: 1
  - symbol: "O"
    value: 1
    category: yellow
    count: 6
  - symbol: "Ó"
    value: 5
    category: red
    count: 1
  - symbol: "P"
    value: 2
    category: green
    count: 3
  - symbol: "R"
    value: 1
    category: yellow
    count: 4
  - symbol: "S"
    value: 1
    category: yellow
    count: 4
  - symbol: "Ś"
    value: 5
    category: red
    count: 1
  - symbol: "T"
    value: 2
    category: green
    count: 3
  - symbol: "U"
    value: 3
    category: blue
    count: 2
  - symbol: "W"
    value: 1
    category: yellow
    count: 4
  - symbol: "Y"
    value: 2
    category: green
    count: 4
  - symbol: "Z"
    value: 1
    category: yellow
    count: 5
  - symbol: "Ź"
    value: 5
    category: red
    count: 1
  - symbol: "Ż"
    value: 5
    category: red
    count: 1
blanks: 2
rack_size: null
